name: Deploy to GitHub Pages

on:
  push:
    branches:
      - feature-nextjs  # 或者你的主分支名称
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write  # 需要写权限来推送gh-pages分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 获取完整的提交历史，以便gh-pages包能正确工作
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and Export
        run: npm run export

      - name: Deploy to gh-pages branch
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
